### ISSUE TITLE
AWB_Setting

### ISSUE THREAD

**Issue by julianheye** [PiddePannkauga/ndviMachine#1]
Good morning from germany, 

i am a newbie and hope, that to open an issue is the right way to ask a question regarding to your ndvi machine. 

I am trying to set up the system with an Pi4, PiNoir cam and an Midopt dualbandpass filter. 
https://midopt.com/filters/db660850/
I got the whole thing working. And the pictures seem to show expected Ndvi values. Thanks for your nice python skripts. 

Now i am trying to figure out, what the best AWB is. How did you set the White balance. I noticed, you set the redAWB to 2.26 and blueAWB to 0.74. Can you tell me how you got to this values? 

I think i have to set the awb to slightly different values because of the different filter behaviour in comph. to the one you used. 

Additionally i want to implement a calibration skript, which could help to get more precise results, also if the lighting conditions change. Therefore i want to set the awb values depending of the lighting conditions. 
I measured some reflection targets with a Stellarwiz Spectrometer to get data of the specific reflexion behavior and i want to calibrate the system each time i use it with setting the awb to a reasoble well value. 

I hope you find some time to answer. And if i am able to get the calibration workflow ready, i could show you the results. 

Thanks in advance Julian

**Comment by PiddePannkauga** [comment]
I just did the calibration manually until I found something that looked decent. Cant really tell you how. My idea was that if things that aren't plants had a "normal" color then I had a good calibration.

**Comment by PiddePannkauga** [comment]
Hope my skripts helped you in your endeavours :D
